language: cpp
dist: xenial
compiler:
  - gcc
  # - clang 

install:
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # proselint
  - sudo pip install proselint
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check
  # doxygen
  - sudo apt-get install -qq doxygen graphviz
  # SFML
  - sudo apt-get install libsfml-dev
  # Creating a booklet
  # - sudo apt-get install pandoc bookletimposer poppler-utils texlive-latex-recommended texlive-extra-utils texlive-fonts-extra

services:
 - xvfb

script: 
  # proselint
  - for filename in `ls *.md`; do proselint $filename; done
  - cd doc
  - for filename in `ls *.md`; do proselint $filename; done
  - cd ..
  # test if all chapters' tests reject and accept answers correctly
  - ./test_tests
  # Check dead links, commented out due to Issue #11
  - cd scripts; ./check_links
  # See if the book can be created
  #- cd scripts
  #- ./create_title_page
  #- ./create_book
