language: cpp
compiler: gcc

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # proselint
  - sudo pip install proselint
  # markdown-link-check, commented out due to Issue #11
  #- sudo apt-get install npm
  #- sudo npm install -g markdown-link-check
  # doxygen
  - sudo apt-get install -qq doxygen graphviz
  # SFML
  - sudo apt-get install libsfml-dev
  # Creating a booklet
  # - sudo apt-get install pandoc bookletimposer poppler-utils texlive-latex-recommended texlive-extra-utils texlive-fonts-extra

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # proselint
  - for filename in `ls *.md`; do proselint $filename; done
  - cd doc
  - for filename in `ls *.md`; do proselint $filename; done
  - cd ..
  # test if all chapters' tests reject and accept answers correctly
  - ./test_tests
  # Check dead links, commented out due to Issue #11
  #- cd scripts; ./check_links
  # See if the book can be created
  #- cd scripts
  #- ./create_title_page
  #- ./create_book
